apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-deploy
  template:
    metadata:
      labels:
        app: echo-deploy
    spec:
      containers:
        - name: echo
          image: mcat1980/echo:3.0
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: echo-configmap
            - secretRef:
                name: echo-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30 # 120s runs keycloak
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30 # 120s runs keycloak
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30
  strategy: { }
status: { }
