apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-deploy
  template:
    metadata:
      labels:
        app: echo-deploy
    spec:
      containers:
        - name: echo
          image: mcat1980/echo:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: echo-configmap
            - secretRef:
                name: echo-secret
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: http
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: http
#            initialDelaySeconds: 15
#            periodSeconds: 5
  strategy: { }
status: { }