apiVersion: v1
kind: Service
metadata:
  name: echo-deploy
spec:
  type: LoadBalancer
  ports:
    - name: 8080-8080
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: echo-deploy
status:
  loadBalancer: {}