apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-deploy
  template:
    metadata:
      labels:
        app: echo-deploy
    spec:
      containers:
        - name: echo
          image: mcat1980/echo:2.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: echo-configmap
            - secretRef:
                name: echo-secret

  strategy: { }
status: { }